/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ShortagesRouteImport } from './routes/shortages'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as FlowRouteImport } from './routes/flow'
import { Route as DelayedRouteImport } from './routes/delayed'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationCodeRouteImport } from './routes/station.$code'
import { Route as BulkCodeRouteImport } from './routes/bulk.$code'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortagesRoute = ShortagesRouteImport.update({
  id: '/shortages',
  path: '/shortages',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowRoute = FlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DelayedRoute = DelayedRouteImport.update({
  id: '/delayed',
  path: '/delayed',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationCodeRoute = StationCodeRouteImport.update({
  id: '/station/$code',
  path: '/station/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkCodeRoute = BulkCodeRouteImport.update({
  id: '/bulk/$code',
  path: '/bulk/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/delayed': typeof DelayedRoute
  '/flow': typeof FlowRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/shortages': typeof ShortagesRoute
  '/status': typeof StatusRoute
  '/warehouse': typeof WarehouseRoute
  '/bulk/$code': typeof BulkCodeRoute
  '/station/$code': typeof StationCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/delayed': typeof DelayedRoute
  '/flow': typeof FlowRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/shortages': typeof ShortagesRoute
  '/status': typeof StatusRoute
  '/warehouse': typeof WarehouseRoute
  '/bulk/$code': typeof BulkCodeRoute
  '/station/$code': typeof StationCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/delayed': typeof DelayedRoute
  '/flow': typeof FlowRoute
  '/issues': typeof IssuesRoute
  '/login': typeof LoginRoute
  '/lookup': typeof LookupRoute
  '/requests': typeof RequestsRoute
  '/settings': typeof SettingsRoute
  '/shortages': typeof ShortagesRoute
  '/status': typeof StatusRoute
  '/warehouse': typeof WarehouseRoute
  '/bulk/$code': typeof BulkCodeRoute
  '/station/$code': typeof StationCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/delayed'
    | '/flow'
    | '/issues'
    | '/login'
    | '/lookup'
    | '/requests'
    | '/settings'
    | '/shortages'
    | '/status'
    | '/warehouse'
    | '/bulk/$code'
    | '/station/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/delayed'
    | '/flow'
    | '/issues'
    | '/login'
    | '/lookup'
    | '/requests'
    | '/settings'
    | '/shortages'
    | '/status'
    | '/warehouse'
    | '/bulk/$code'
    | '/station/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/calendar'
    | '/delayed'
    | '/flow'
    | '/issues'
    | '/login'
    | '/lookup'
    | '/requests'
    | '/settings'
    | '/shortages'
    | '/status'
    | '/warehouse'
    | '/bulk/$code'
    | '/station/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  DelayedRoute: typeof DelayedRoute
  FlowRoute: typeof FlowRoute
  IssuesRoute: typeof IssuesRoute
  LoginRoute: typeof LoginRoute
  LookupRoute: typeof LookupRoute
  RequestsRoute: typeof RequestsRoute
  SettingsRoute: typeof SettingsRoute
  ShortagesRoute: typeof ShortagesRoute
  StatusRoute: typeof StatusRoute
  WarehouseRoute: typeof WarehouseRoute
  BulkCodeRoute: typeof BulkCodeRoute
  StationCodeRoute: typeof StationCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortages': {
      id: '/shortages'
      path: '/shortages'
      fullPath: '/shortages'
      preLoaderRoute: typeof ShortagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow': {
      id: '/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof FlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delayed': {
      id: '/delayed'
      path: '/delayed'
      fullPath: '/delayed'
      preLoaderRoute: typeof DelayedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$code': {
      id: '/station/$code'
      path: '/station/$code'
      fullPath: '/station/$code'
      preLoaderRoute: typeof StationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk/$code': {
      id: '/bulk/$code'
      path: '/bulk/$code'
      fullPath: '/bulk/$code'
      preLoaderRoute: typeof BulkCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  DelayedRoute: DelayedRoute,
  FlowRoute: FlowRoute,
  IssuesRoute: IssuesRoute,
  LoginRoute: LoginRoute,
  LookupRoute: LookupRoute,
  RequestsRoute: RequestsRoute,
  SettingsRoute: SettingsRoute,
  ShortagesRoute: ShortagesRoute,
  StatusRoute: StatusRoute,
  WarehouseRoute: WarehouseRoute,
  BulkCodeRoute: BulkCodeRoute,
  StationCodeRoute: StationCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
