/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as ShortagesRouteImport } from './routes/shortages'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationCodeRouteImport } from './routes/station.$code'
import { Route as BulkCodeRouteImport } from './routes/bulk.$code'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortagesRoute = ShortagesRouteImport.update({
  id: '/shortages',
  path: '/shortages',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationCodeRoute = StationCodeRouteImport.update({
  id: '/station/$code',
  path: '/station/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkCodeRoute = BulkCodeRouteImport.update({
  id: '/bulk/$code',
  path: '/bulk/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/shortages': typeof ShortagesRoute
  '/warehouse': typeof WarehouseRoute
  '/bulk/$code': typeof BulkCodeRoute
  '/station/$code': typeof StationCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/shortages': typeof ShortagesRoute
  '/warehouse': typeof WarehouseRoute
  '/bulk/$code': typeof BulkCodeRoute
  '/station/$code': typeof StationCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/requests': typeof RequestsRoute
  '/shortages': typeof ShortagesRoute
  '/warehouse': typeof WarehouseRoute
  '/bulk/$code': typeof BulkCodeRoute
  '/station/$code': typeof StationCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/login'
    | '/requests'
    | '/shortages'
    | '/warehouse'
    | '/bulk/$code'
    | '/station/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/login'
    | '/requests'
    | '/shortages'
    | '/warehouse'
    | '/bulk/$code'
    | '/station/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/login'
    | '/requests'
    | '/shortages'
    | '/warehouse'
    | '/bulk/$code'
    | '/station/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  RequestsRoute: typeof RequestsRoute
  ShortagesRoute: typeof ShortagesRoute
  WarehouseRoute: typeof WarehouseRoute
  BulkCodeRoute: typeof BulkCodeRoute
  StationCodeRoute: typeof StationCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortages': {
      id: '/shortages'
      path: '/shortages'
      fullPath: '/shortages'
      preLoaderRoute: typeof ShortagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/$code': {
      id: '/station/$code'
      path: '/station/$code'
      fullPath: '/station/$code'
      preLoaderRoute: typeof StationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk/$code': {
      id: '/bulk/$code'
      path: '/bulk/$code'
      fullPath: '/bulk/$code'
      preLoaderRoute: typeof BulkCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  RequestsRoute: RequestsRoute,
  ShortagesRoute: ShortagesRoute,
  WarehouseRoute: WarehouseRoute,
  BulkCodeRoute: BulkCodeRoute,
  StationCodeRoute: StationCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
